<?php

namespace ReplyBundle\Repository;

/**
 * ConsultantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultantRepository extends \Doctrine\ORM\EntityRepository
{
}
