<?php

namespace ReplyBundle\Repository;

/**
 * JuniorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuniorRepository extends \Doctrine\ORM\EntityRepository
{
}
