<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerRtfmnke\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerRtfmnke/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerRtfmnke\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRtfmnke\appDevDebugProjectContainer();
